# See reference docs at
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: ci
on: [push, pull_request]

jobs:
  # Runs only for pull requests due to base_ref eval'ed to false otherwise.
  build:
    runs-on: ubuntu-20.04
    if: ${{github.base_ref}}
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      - name: Build container image
        run: docker build -f Containerfile .
